volumes:
  finance_backend_local_postgres_data: {}
  finance_backend_local_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: finance_backend_local_django
    container_name: finance_backend_local_django
    depends_on:
      - postgres
    volumes:
      - ./finance_backend:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - 8000:8000
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: finance_backend_production_postgres
    container_name: finance_backend_local_postgres
    volumes:
      - finance_backend_local_postgres_data:/var/lib/postgresql/data
      - finance_backend_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  vite:
    build:
      context: .
      dockerfile: ./compose/local/vite/Dockerfile
    image: finance_frontend_local_vite
    container_name: finance_frontend_local_vite
    volumes:
      - ./finance_frontend:/app:z
    env_file:
      - ./.envs/.local/.vite
    ports:
      - 5173:5173