volumes:
  finance_backend_local_postgres_data: {}
  finance_backend_local_postgres_data_backups: {}
  node_modules: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: finance_backend_local_django
    container_name: finance_backend_local_django
    depends_on:
      - postgres
    volumes:
      - ./finance_backend:/app
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - 8000:8000
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: finance_backend_production_postgres
    container_name: finance_backend_local_postgres
    volumes:
      - finance_backend_local_postgres_data:/var/lib/postgresql/data
      - finance_backend_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  vite:
    build:
      context: .
      dockerfile: ./compose/local/vite/Dockerfile
    image: finance_frontend_local_vite
    container_name: finance_frontend_local_vite
    volumes:
      - ./finance_frontend/src:/work/src
    env_file:
      - ./.envs/.local/.vite
    ports:
      - 8080:8080

  vite-test:
    build:
      context: .
      dockerfile: ./compose/local/vite/Dockerfile
    image: finance_frontend_local_vite_test
    container_name: finance_frontend_local_test
    volumes:
      - ./finance_frontend:/work
      - node_modules:/work/node_modules
    command: yarn test
