# Generated by Django 5.0.13 on 2025-03-26 05:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("money", "0003_alter_item_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accountsnapshot",
            name="currency",
        ),
        migrations.RemoveField(
            model_name="exchange",
            name="exchange_brokder",
        ),
        migrations.AddField(
            model_name="account",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("CHECKING_ACCOUNT", "입출금"),
                    ("SAVINGS_ACCOUNT", "저금"),
                    ("INSTALLMENT_SAVING", "적금"),
                    ("TIME_DEPOSIT", "예금"),
                    ("CREDIT_CARD", "신용카드"),
                    ("STOCK", "주식"),
                    ("LOAN", "대출"),
                ],
                default="CHECKING_ACCOUNT",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="exchange",
            name="exchange_broker",
            field=models.CharField(
                choices=[
                    ("ETC", "기타"),
                    ("BANK", "은행"),
                    ("WIREBARLEY", "와이어바알리"),
                    ("CREDITCARD", "신용카드"),
                ],
                default="ETC",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="currency",
            field=models.CharField(
                choices=[("KRW", "원화"), ("USD", "달러")], default="USD", max_length=3
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="nickname",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="bank",
            name="country",
            field=models.CharField(
                choices=[("KOREA", "한국"), ("USA", "미국")],
                default="KOREA",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="exchange",
            name="currency_from",
            field=models.CharField(
                choices=[("KRW", "원화"), ("USD", "달러")], default="USD", max_length=3
            ),
        ),
        migrations.AlterField(
            model_name="exchange",
            name="currency_to",
            field=models.CharField(
                choices=[("KRW", "원화"), ("USD", "달러")], default="USD", max_length=3
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="currency",
            field=models.CharField(
                choices=[("KRW", "원화"), ("USD", "달러")], default="USD", max_length=3
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="item_type",
            field=models.CharField(
                choices=[("ITEM", "아이템"), ("STOCK", "주식")],
                default="ITEM",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="itemprice",
            name="currency",
            field=models.CharField(
                choices=[("KRW", "원화"), ("USD", "달러")], default="USD", max_length=3
            ),
        ),
        migrations.AlterField(
            model_name="itemtransaction",
            name="note",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="retailer",
            name="category",
            field=models.CharField(
                choices=[
                    ("ETC_INCOME", "기타소득"),
                    ("SALARY", "월급"),
                    ("BONUS", "보너스"),
                    ("INTEREST_INCOME", "이자소득"),
                    ("STOCK_INCOME", "주식"),
                    ("RENT_INCOME", "임대"),
                    ("DIVIDEND", "배당"),
                    ("DEPOSIT", "입금"),
                    ("ETC_EXPENSE", "기타지출"),
                    ("DAILY_NECESSITY", "생필품"),
                    ("GROCERY", "식료품"),
                    ("MEMBERSHIP", "맴버십"),
                    ("SERVICE", "서비스"),
                    ("EAT_OUT", "외식"),
                    ("CLOTHING", "옷"),
                    ("PRESENT", "선물"),
                    ("CAR", "이동수단"),
                    ("HOUSING", "월세"),
                    ("LEISURE", "여가"),
                    ("MEDICAL", "의료"),
                    ("PARENTING", "육아"),
                    ("INTEREST_EXPENSE", "이자지출"),
                    ("WITHDRAW", "출금"),
                    ("TRANSFER", "이체"),
                    ("UNKNOWN", "알 수 없음"),
                ],
                default="UNKNOWN",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="retailer",
            name="retailer_type",
            field=models.CharField(
                choices=[
                    ("ETC", "기타"),
                    ("STORE", "상점"),
                    ("PERSON", "개인"),
                    ("BANK", "은행"),
                    ("SERVICE", "서비스"),
                    ("INCOME", "수입"),
                    ("RESTAURANT", "식당"),
                    ("INTERNET", "인터넷"),
                ],
                default="ETC",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="salary",
            name="currency",
            field=models.CharField(
                choices=[("KRW", "원화"), ("USD", "달러")], default="USD", max_length=3
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="note",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("ETC_INCOME", "기타소득"),
                    ("SALARY", "월급"),
                    ("BONUS", "보너스"),
                    ("INTEREST_INCOME", "이자소득"),
                    ("STOCK_INCOME", "주식"),
                    ("RENT_INCOME", "임대"),
                    ("DIVIDEND", "배당"),
                    ("DEPOSIT", "입금"),
                    ("ETC_EXPENSE", "기타지출"),
                    ("DAILY_NECESSITY", "생필품"),
                    ("GROCERY", "식료품"),
                    ("MEMBERSHIP", "맴버십"),
                    ("SERVICE", "서비스"),
                    ("EAT_OUT", "외식"),
                    ("CLOTHING", "옷"),
                    ("PRESENT", "선물"),
                    ("CAR", "이동수단"),
                    ("HOUSING", "월세"),
                    ("LEISURE", "여가"),
                    ("MEDICAL", "의료"),
                    ("PARENTING", "육아"),
                    ("INTEREST_EXPENSE", "이자지출"),
                    ("WITHDRAW", "출금"),
                    ("TRANSFER", "이체"),
                    ("UNKNOWN", "알 수 없음"),
                ],
                default="UNKNOWN",
                max_length=30,
            ),
        ),
    ]
