# Generated by Django 5.0.13 on 2025-03-26 06:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("money", "0004_remove_accountsnapshot_currency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountsnapshot",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
            preserve_default=False,
        ),
    ]
