# Generated by Django 5.0.13 on 2025-03-26 07:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("money", "0006_alter_salary_options_alter_retailer_retailer_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="itemtransaction",
            name="amount",
        ),
    ]
