# Generated by Django 5.0.13 on 2025-03-27 06:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("money", "0007_remove_itemtransaction_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="nickname",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
