# Generated by Django 5.0.13 on 2025-03-29 20:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("money", "0008_alter_account_nickname"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="currency",
        ),
    ]
