# Generated by Django 5.0.13 on 2025-03-29 20:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("money", "0009_remove_item_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemprice",
            name="note",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="itemprice",
            name="source",
            field=models.CharField(default="", max_length=20),
        ),
    ]
