# Generated by Django 5.2 on 2025-04-21 04:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("money", "0011_alter_retailer_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("CHECKING_ACCOUNT", "입출금"),
                    ("SAVINGS_ACCOUNT", "저금"),
                    ("INSTALLMENT_SAVING", "적금"),
                    ("TIME_DEPOSIT", "예금"),
                    ("CREDIT_CARD", "신용카드"),
                    ("REAL_ESTATE", "부동산"),
                    ("STOCK", "주식"),
                    ("LOAN", "대출"),
                ],
                default="CHECKING_ACCOUNT",
                max_length=20,
            ),
        ),
    ]
