# Generated by Django 5.2 on 2025-05-05 07:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("money", "0012_alter_account_account_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="retailer",
            name="category",
            field=models.CharField(
                choices=[
                    ("ETC_INCOME", "기타소득"),
                    ("SALARY", "월급"),
                    ("BONUS", "보너스"),
                    ("INTEREST_INCOME", "이자소득"),
                    ("STOCK_INCOME", "주식"),
                    ("RENT_INCOME", "임대"),
                    ("DIVIDEND", "배당"),
                    ("DEPOSIT", "입금"),
                    ("ETC_EXPENSE", "기타지출"),
                    ("DAILY_NECESSITY", "생필품"),
                    ("GROCERY", "식료품"),
                    ("MEMBERSHIP", "맴버십"),
                    ("SERVICE", "서비스"),
                    ("EAT_OUT", "외식"),
                    ("ELECTRONICS", "전자기기"),
                    ("CLOTHING", "옷"),
                    ("PRESENT", "선물"),
                    ("CAR", "이동수단"),
                    ("COMMUNICATION", "통신"),
                    ("HOUSING", "월세"),
                    ("LEISURE", "여가"),
                    ("MEDICAL", "의료"),
                    ("PARENTING", "육아"),
                    ("INTEREST_EXPENSE", "이자지출"),
                    ("WITHDRAW", "출금"),
                    ("TRANSFER", "이체"),
                    ("UNKNOWN", "알 수 없음"),
                ],
                default="UNKNOWN",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("ETC_INCOME", "기타소득"),
                    ("SALARY", "월급"),
                    ("BONUS", "보너스"),
                    ("INTEREST_INCOME", "이자소득"),
                    ("STOCK_INCOME", "주식"),
                    ("RENT_INCOME", "임대"),
                    ("DIVIDEND", "배당"),
                    ("DEPOSIT", "입금"),
                    ("ETC_EXPENSE", "기타지출"),
                    ("DAILY_NECESSITY", "생필품"),
                    ("GROCERY", "식료품"),
                    ("MEMBERSHIP", "맴버십"),
                    ("SERVICE", "서비스"),
                    ("EAT_OUT", "외식"),
                    ("ELECTRONICS", "전자기기"),
                    ("CLOTHING", "옷"),
                    ("PRESENT", "선물"),
                    ("CAR", "이동수단"),
                    ("COMMUNICATION", "통신"),
                    ("HOUSING", "월세"),
                    ("LEISURE", "여가"),
                    ("MEDICAL", "의료"),
                    ("PARENTING", "육아"),
                    ("INTEREST_EXPENSE", "이자지출"),
                    ("WITHDRAW", "출금"),
                    ("TRANSFER", "이체"),
                    ("UNKNOWN", "알 수 없음"),
                ],
                default="UNKNOWN",
                max_length=30,
            ),
        ),
    ]
