# ==== pytest ====
[tool.pytest.ini_options]
minversion = "6.0"
addopts = "--ds=config.settings.test --reuse-db --import-mode=importlib"
python_files = [
    "tests.py",
    "test_*.py",
]

# ==== isort ====
[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 88

# ==== Coverage ====
[tool.coverage.run]
include = ["finance_backend/**"]
omit = ["*/migrations/*", "*/tests/*"]
plugins = ["django_coverage_plugin"]

# ==== mypy ====
[tool.mypy]
python_version = "3.12"
check_untyped_defs = true
ignore_missing_imports = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_unused_configs = true
disallow_untyped_defs = false
disallow_incomplete_defs = false
implicit_optional = true
disable_error_code = ["attr-defined", "var-annotated", "misc", "arg-type", "return-value", "list-item", "assignment"]
plugins = [
    "mypy_django_plugin.main",
    "mypy_drf_plugin.main",
]

[[tool.mypy.overrides]]
# Django migrations should not produce any errors:
module = "*.migrations.*"
ignore_errors = true

[[tool.mypy.overrides]]
# Django models 타입 에러 무시:
module = "*.models.*"
disallow_untyped_defs = false
disable_error_code = ["var-annotated", "attr-defined", "misc", "assignment"]
ignore_errors = true

[[tool.mypy.overrides]]
# API 타입 에러 무시:
module = "*.api.*"
disallow_untyped_defs = false
disable_error_code = ["var-annotated", "arg-type", "attr-defined"]
ignore_errors = true

[[tool.mypy.overrides]]
# 설정 파일 타입 에러 무시:
module = "*.settings.*"
ignore_errors = true

[[tool.mypy.overrides]]
# contrib 모듈 타입 에러 무시:
module = "*.contrib.*"
ignore_errors = true

[[tool.mypy.overrides]]
# views 모듈 타입 에러 무시:
module = "*.views.*"
ignore_errors = true

[tool.django-stubs]
django_settings_module = "config.settings.test"

# ==== djLint ====
[tool.djlint]
blank_line_after_tag = "load,extends"
close_void_tags = true
format_css = true
format_js = true
# TODO: remove T002 when fixed https://github.com/djlint/djLint/issues/687
ignore = "H006,H030,H031,T002"
include = "H017,H035"
indent = 2
max_line_length = 119
profile = "django"

[tool.djlint.css]
indent_size = 2

[tool.djlint.js]
indent_size = 2
